name: PR Size Watcher
on: [pull_request]

jobs:
  pr-size:
    name: Check PR size
    runs-on: ubuntu-latest
    steps:
      - uses: ookami-kb/gh-pr-size-watcher@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # required
          warningSize: 300 # optional
          warningMessage: ':warning: PR has more than **{allowed} additions**. Consider splitting it into smaller PRs.' # optional
          excludeTitle: 'PR_SIZE_SKIP' # to skip validation if PR title matches regex, optional
          excludePaths:  | # to exclude some files from calculation, optional
            README.md
            *.json
          excludeLabels:  | # to skip validation if PR labels contain one of these, optional
            skip-size-check
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '100'
          m_label: 'size/m'
          m_max_size: '500'
          l_label: 'size/l'
          l_max_size: '1000'
          xl_label: 'size/xl'
          fail_if_xl: 'true'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          github_api_url: 'api.github.com'
          files_to_ignore: |
            "pnpm-lock.yaml"
            "*.md"
            "*.json"
